# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# search_url: The URL for performing the search
# loaded_link: URL to the 'native' interface
# object_types: aspace object types to return. these are mapped to Solr types:
# field queries
# query_params: params to be passed to Solr
# native_query_params: params to be passed to the loaded_link.

defaults: &defaults
  search_url: 'http://localhost:8090/collection1/select'
  loaded_link: 'http://localhost:8081/search'
  no_results_link: 'http://localhost:8081' 
  object_types:
    - subject
    - classification
    - accession
    - repository
    - resource
    - agent
    - digital_object
    - archival_object
  query_params:
    q:
      - 'publish:true'
      - 'types:pui' 
    fq:
      - '-exclude_by_default:true'
      - 'publish:true'
      - 'suppressed:false'
    rows: 3
    wt: 'json'
  native_query_params:
    op: ['']
    q: []
    

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
